name: Github Actions Example

on:
  push:
    branches: [ master, main ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test java project
        uses: vignesh1424/java-ci-workflow@main
 